feat: APPS-2294 Add PageAnchor to default layout
UCLALibrary/library-website-nuxt pull request #706
Opened 2023-05-22 17:39 UTC by jendiamond

Connected to [APPS-](https://jira.library.ucla.edu/browse/APPS-)

**Page/Pages Created/updated:** {filename}.vue from #{issue number}

**Notes:**

{Any notes about what you built. How does it work? Anything missing?}

**Time Report:**

This took me {x} hours to build this.

**Checklist:**

-   [ ] I added github label for semantic versioning
-   [ ] I double checked it looks like the designs
-   [ ] I completed any required mobile breakpoint styling
-   [ ] I completed any required hover state styling
-   [ ] I included a working spec file
-   [ ] I added notes above about how long it took to build this component
-   [ ] UX has reviewed this PR
-   [ ] I assigned this PR to someone to review

2023-05-25 00:39 UTC, jendiamond commented on app/router.scrollBehavior.js
Deletes extra lines and white spaces

2023-07-28 17:32 UTC, pghorpade requested changes

2023-07-28 17:32 UTC, pghorpade commented on cypress/e2e/collectiondetailpage.cy.js
> +
this does not belong to collection detail

2023-07-28 17:32 UTC, pghorpade commented on nuxt.config.js
> +        { src: '~/plugins/get-headers.js', mode: 'client' },
rename the file to be .client.js, and remove mode, this is pattern we are following

2023-07-31 17:10 UTC, pghorpade requested changes

2023-07-31 17:10 UTC, pghorpade commented on cypress/e2e/collectionsexplorepage.cy.js
> -        cy.get(".page-collections-explore").should("be.visible")
@jendiamond I am not sure why this is removed.

2023-07-31 17:10 UTC, pghorpade commented on nuxt.config.js
> +        "~/plugins/get-headers.js",
Rename it to get-headers.client.js

2023-07-31 22:02 UTC, pghorpade approved these changes
💯 🍰

2023-08-01 16:10 UTC, merged