fix: APPS-2300_remove-donor-filter
UCLALibrary/library-website-nuxt pull request #714
Opened 2023-07-28 00:02 UTC by jendiamond

Connected to [APPS-2300](https://jira.library.ucla.edu/browse/APPS-2300)

commented out donor filter

2023-07-28 17:36 UTC, pghorpade requested changes

2023-07-28 17:36 UTC, pghorpade commented on pages/give/endowments/index.vue
> +        <!-- <search-generic
we only want to remove the donor filter and keep the search, see services and resource listing page for no filters example

2023-08-08 20:32 UTC, pghorpade submitted a review, later dismissed

2023-08-08 20:32 UTC, pghorpade commented on pages/give/endowments/index.vue
> +                // config.endowmentsList.filters
Here you may have to pass  []

2023-08-09 20:44 UTC, sourcefilter approved these changes

2023-08-09 20:44 UTC, merged