feat: APPS-2340 robots.txt, listing page for impact reports
UCLALibrary/library-website-nuxt pull request #720
Opened 2023-08-14 18:03 UTC by sourcefilter

Connected to [APPS-1903](https://jira.library.ucla.edu/browse/APPS-1903)
Connected to [APPS-2340](https://jira.library.ucla.edu/browse/APPS-2340)

https://deploy-preview-720--uclalibrary-test.netlify.app/impact/all
redirects to:
https://deploy-preview-720--uclalibrary-test.netlify.app/about/reports/

https://deploy-preview-720--uclalibrary-test.netlify.app/impact/
redirects to the current years impact report
https://deploy-preview-720--uclalibrary-test.netlify.app/impact/

2023-08-16 17:56 UTC, axamei requested changes
Getting 404s on link, but that might be an env issue. Add the global call to action block and this should be good to go. Thanks!

2023-08-16 17:56 UTC, axamei commented on pages/about/reports/index.vue
>      </main>
Let's add the global call to action block:
```
        <section-wrapper>
            <block-call-to-action
                class="block-call-to-action"
                :is-global="true"
            />
        </section-wrapper>
```

2023-08-16 17:56 UTC, axamei commented on static/_redirects
> +/impact/all	/about/reports
I am getting a 404 when I click on the links. Do redirects work in test?

2023-08-17 19:52 UTC, axamei submitted a review, later dismissed

2023-08-18 17:45 UTC, jendiamond approved these changes
🥮

2023-08-18 18:09 UTC, merged